[package]
name = "aerial-registry"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.13", default-features = false, features = ["native-tls", "json"] }
reqwest-middleware = { version = "0.5", features = ["json"] }
backon = "1"
async-trait = "0.1"
http = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
flate2 = "1"
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
futures = "0.3"
toml = "0.8"
config = { version = "0.15", default-features = false, features = ["toml"] }
rusqlite = { version = "0.40.1", features = ["bundled"] }
chrono = { version = "0.4.45", default-features = false, features = ["clock"] }

[dev-dependencies]
tokio = { version = "1", features = ["test-util"] }
